# Generated by Django 6.0.1 on 2026-01-23 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='appplicant',
            new_name='applicant',
        ),
    ]
