# Generated by Django 4.2.7 on 2026-02-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_application_id_alter_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 years (Fresher)'), ('1-3', '1-3 years (Junior)'), ('3-5', '3-5 years (Mid-level)'), ('5-8', '5-8 years (Senior)'), ('8+', '8+ years (Lead)')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
