# Generated by Django 4.2.7 on 2026-02-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume',
        ),
    ]
